### ISSUE TITLE
Return tuple instead of string

### ISSUE THREAD

**Issue by JeffreyCA** [lttkgp/youtube_title_parse#3]
Is it possible to have `get_artist_title` return a tuple `(artist, title)` instead of a string, like how [get-artist-title](https://www.npmjs.com/package/get-artist-title) works?

Right now I want to get the parsed artist and title individually, but right now it returns a combined string which I have to split on `-`.

**Comment by ghostwriternr** [comment]
@JeffreyCA thanks for the feature request! I was hoping to do it eventually too. Thanks for the nudge.

[Available as part of version 1.0.0b3](https://pypi.org/project/youtube-title-parse/1.0.0b3/) 😄 
Will try and get better at writing release notes soon.

**Comment by ghostwriternr** [comment]
Closing this issue for now. Please do reopen if you still see any inconsistencies / open a new issue for anything else.

**Comment by JeffreyCA** [comment]
That was quick, thank you so much!
