### ISSUE TITLE
Make unit tests more readable

### ISSUE THREAD

**Issue by ghostwriternr** [lttkgp/youtube_title_parse#7]
Unit tests currently look like:
```py
{
    "input": "Boats & BIrds - Gregory & the Hawk",
    "expected": ["Boats & BIrds", "Gregory & the Hawk"],
}
```
but it not entirely clear what the `expected` array is. Considering changing it to:
```py
{
    "input": "Boats & BIrds - Gregory & the Hawk",
    "expected": {
        "artist": "Boats & BIrds",
        "title": "Gregory & the Hawk"
    },
}
```

Might also be a good time to consider if the return type of the module is best suited as a tuple or dict.

**Comment by shunjid** [comment]
Hi,
I would love to contribute. But can you please elaborate it with more details?

**Comment by ghostwriternr** [comment]
Hi @shunjid! I'm so sorry for not noticing this issue sooner. In the time that has passed since we created this, the project has settled on using tuples as the return value and this change is no longer needed. I'll make sure I update the README right away to highlight this. Closing this issue.
